### ISSUE TITLE
Covariates: Functions for downloading covariate data

### ISSUE THREAD

**Issue by mitchellmanware** [Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel#25]

**Comment by mitchellmanware** [comment]
@sigmafelix 
Can you try the patched function on branch mm_noaa_smoke_patch_1103.
Updated lines should accommodate input ranges that span different months and years

**Comment by sigmafelix** [comment]
Thank you @mitchellmanware for the prompt response. The patch works well. I directly pushed a change at the file in your patch branch to remove Sys.sleep.

**Comment by mitchellmanware** [comment]
@sigmafelix 
Great, thank you. The patch branch I created got somewhat muddled with un-merged changes on another branch, so I will clean this up and create a new pull request with both of our changes to `download_noaa_smoke_data.R`.

**Comment by mitchellmanware** [comment]
New pull requested created after adding `lintr` requirements to `download_noaa_smoke_data.R

**Comment by sigmafelix** [comment]
@mitchellmanware 

When running `download_noaa_hms_smoke_data` multiple times* In the same session, I found that the unzipped shapefiles got a string _Shapefile_ appended its name at each iteration. It will not allow unzipping shapefiles to the target directory due to the path length limitation (maybe 255 characters).  I think the name error came from line 149 at [file](https://github.com/Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel/blob/main/input/Rinput/download_functions/download_noaa_hms_smoke_data.R) as the file format is already included in zip file names. In addition to fixing this line, perhaps an additional argument of `unzip` would be helpful to allow users to keep zip files only.


*The reason I ran the function multiple times (6 months per run) was that bulk download (e.g., for 1+ years) returned network errors.

**Comment by mitchellmanware** [comment]
@sigmafelix 

The appending of "Shapefile" to the file name was to help differentiate the reading of shapefiles and KML files within the same directory. I will work to change this.

The `remove_download` argument in the function is equal to your recommended `unzip` argument. The default is set to `TRUE` (removes zip files), but as in your experience having the default set to retain zip files may be better. I will check back in soon.

**Comment by mitchellmanware** [comment]
@sigmafelix 

The following changes have been made to the `download_noaa_hms_smoke_data` function

1. Removed the "file.rename()` step to avoid "hms_smoke_Shapefile_Shapefile..." if function used iteratively
2. Added `unzip =` argument if user wishes to download only zip files
3. Changed default setting of `remove_zip` to `FALSE` so user cannot unknowingly remove the zip files.
4. Removed unnecessary code related to `data_format = "KML"` because many of the arguments (`unzip =`, `remove_zip = `, `directory_to_download =`) do not apply.
5. Removed the `url_noaa_hms_smoke_data` from arguments. User has no reason to edit the base used to form the download URLs. Changing can only make the function fail. Having as an argument has no benefit.

Please find all changes reflected in branch `mm_noaa_download_patch_1114`. I will wait to discuss further before any pull requests are made

**Comment by sigmafelix** [comment]
@mitchellmanware 
Thank you for the update. I tested the function and it works well. I pushed a minor change to your patch branch.

**Comment by mitchellmanware** [comment]
@sigmafelix 

Thank you for the contribution. I will open a pull request shortly. On a related note, I am going back through all of the download functions to check for bugs similar to those identified in the `download_noaa_hms_smoke_data` function, to add an `unzip` argument (where applicable), and to set the `remove_zip` default to `FALSE`. I will create a new branch to patch these potential bugs.

**Comment by sigmafelix** [comment]
@mitchellmanware All look great. Thank you for the hard work!
